### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by rupak0577**
Self-explanatory

### CODE REVIEW

**Comment by sils** [comment]
lgtm on first sight

**Comment by sils** [comment]
we don't have rultor or gitmate here?

**Comment by Adrianzatreanu** [comment]
this still going :D ?

**Comment by sils** [comment]
@Udayan12167 please check this. Do we want to close down the coala-gui project in favour of coala-html? I think the latter has more potential and there's no need to develop both.

**Pull request closed without merging**
